import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#0A0F2C",
		padding: 24,
		justifyContent: "center",
		position: "relative",
	},
	bubbleTop: {
		position: "absolute",
		top: -160,
		right: -140,
		width: 320,
		height: 320,
		borderRadius: 160,
		backgroundColor: "rgba(99, 102, 241, 0.18)",
	},
	bubbleBottom: {
		position: "absolute",
		bottom: -180,
		left: -160,
		width: 360,
		height: 360,
		borderRadius: 180,
		backgroundColor: "rgba(34, 211, 238, 0.12)",
	},
	card: {
		backgroundColor: "#0F172A",
		borderRadius: 16,
		padding: 20,
		borderWidth: 1,
		borderColor: "rgba(99, 102, 241, 0.2)",
		shadowColor: "#6366F1",
		shadowOpacity: 0.28,
		shadowRadius: 14,
		elevation: 6,
	},
	heroIcon: {
		alignSelf: "center",
		marginBottom: 24,
	},
	heading: {
		color: "#E2E8F0",
		fontSize: 28,
		fontWeight: "800",
		marginBottom: 8,
		textAlign: "center",
		alignSelf: "center",
	},
	subheading: {
		color: "#94A3B8",
		fontSize: 14,
		marginBottom: 18,
		lineHeight: 20,
		textAlign: "center",
		alignSelf: "center",
	},
	pill: {
		alignSelf: "flex-start",
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 7,
		borderRadius: 999,
		backgroundColor: "rgba(99, 102, 241, 0.14)",
		borderWidth: 1,
		borderColor: "rgba(99, 102, 241, 0.24)",
		marginBottom: 20,
		marginTop: 24,
	},
	pillText: {
		color: "#E2E8F0",
		fontWeight: "700",
		fontSize: 13,
		letterSpacing: 0.2,
	},
	input: {
		backgroundColor: "#0F172A",
		color: "#E2E8F0",
		borderRadius: 12,
		paddingHorizontal: 16,
		paddingVertical: 14,
		borderWidth: 1,
		borderColor: "#1E293B",
		marginBottom: 39,
	},
	button: {
		backgroundColor: "#6366F1",
		paddingVertical: 14,
		borderRadius: 12,
		alignItems: "center",
		shadowColor: "#6366F1",
		shadowOpacity: 0.3,
		shadowRadius: 10,
		elevation: 5,
	},
	buttonText: {
		color: "white",
		fontWeight: "800",
	},
	errorText: {
		color: "#EF4444",
		marginBottom: 10,
	},
});
