import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#010a30ff",
	},
	screenContent: {
		paddingBottom: 40,
		paddingTop: 8,
	},
	heroCard: {
		marginHorizontal: 20,
		marginTop: 24,
		marginBottom: 16,
		padding: 20,
		borderRadius: 18,
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.18)",
		shadowColor: "#0EA5E9",
		shadowOpacity: 0.25,
		shadowRadius: 12,
		elevation: 5,
		gap: 6,
	},
	heroGreeting: {
		color: "#94A3B8",
		fontSize: 14,
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	heroName: {
		color: "#E2E8F0",
		fontSize: 30,
		fontWeight: "900",
		marginTop: 2,
	},
	heroSubtitle: {
		color: "#CBD5E1",
		fontSize: 15,
		marginTop: 6,
		lineHeight: 20,
	},
	bubbleTop: {
		position: "absolute",
		top: -120,
		right: -100,
		width: 280,
		height: 280,
		borderRadius: 140,
		backgroundColor: "#0EA5E9",
		opacity: 0.15,
	},
	bubbleBottom: {
		position: "absolute",
		bottom: -140,
		left: -120,
		width: 320,
		height: 320,
		borderRadius: 160,
		backgroundColor: "#22D3EE",
		opacity: 0.1,
	},
	quickActionsRow: {
		flexDirection: "row",
		gap: 12,
		paddingHorizontal: 20,
		marginBottom: 14,
	},
	quickAction: {
		flex: 1,
		paddingVertical: 14,
		paddingHorizontal: 16,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.18)",
		backgroundColor: "#0F172A",
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		shadowColor: "#0EA5E9",
		shadowOpacity: 0.25,
		shadowRadius: 12,
		elevation: 5,
		overflow: "hidden",
		position: "relative",
	},
	quickActionIconWrap: {
		width: 44,
		height: 44,
		borderRadius: 14,
		alignItems: "center",
		justifyContent: "center",
	},
	quickActionTextWrap: {
		flex: 1,
		gap: 2,
		marginLeft: 10,
	},
	quickActionTitle: {
		color: "#E2E8F0",
		fontSize: 17,
		fontWeight: "800",
		marginBottom: 2,
	},
	quickActionSubtitle: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 18,
	},
	languageRow: {
		flexDirection: "row",
		alignItems: "center",
		marginTop: 24,
	},
	languageLabel: {
		color: "#CBD5E1",
		marginRight: 8,
	},
	languageButton: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		marginHorizontal: 4,
		borderWidth: 1,
		borderRadius: 6,
		backgroundColor: "white",
		borderColor: "gray",
	},
	languageButtonActive: {
		backgroundColor: "#e0e0e0",
		borderColor: "black",
	},
	cardsContainer: {
		paddingHorizontal: 20,
		paddingTop: 12,
		paddingBottom: 32,
		gap: 20,
	},
	card: {
		borderRadius: 18,
	},
	cardImage: {
		width: "100%",
		height: 260,
		justifyContent: "flex-end",
	},
	cardImageRadius: {
		borderRadius: 18,
	},
	cardOverlay: {
		...StyleSheet.absoluteFillObject,
		borderRadius: 18,
		backgroundColor: "rgba(0, 0, 0, 0.3)",
	},
	cardContent: {
		padding: 16,
		gap: 4,
	},
	cardTitle: {
		fontSize: 22,
		fontWeight: "900",
		color: "#E2E8F0",
	},
	cardSubtitle: {
		fontSize: 13,
		color: "#CBD5E1",
		lineHeight: 18,
	},
});
