import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#010a30ff",
	},
	heroCard: {
		marginHorizontal: 20,
		marginTop: 24,
		marginBottom: 16,
		padding: 18,
		borderRadius: 18,
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.06)",
		shadowColor: "#000",
		shadowOpacity: 0.3,
		shadowRadius: 10,
		elevation: 4,
	},
	heroGreeting: {
		color: "#94A3B8",
		fontSize: 13,
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	heroName: {
		color: "#E2E8F0",
		fontSize: 28,
		fontWeight: "900",
		marginTop: 4,
	},
	heroSubtitle: {
		color: "#CBD5E1",
		fontSize: 15,
		marginTop: 8,
		lineHeight: 20,
	},
	bubbleTop: {
		position: "absolute",
		top: -120,
		right: -100,
		width: 280,
		height: 280,
		borderRadius: 140,
		backgroundColor: "#0EA5E9",
		opacity: 0.15,
	},
	bubbleBottom: {
		position: "absolute",
		bottom: -140,
		left: -120,
		width: 320,
		height: 320,
		borderRadius: 160,
		backgroundColor: "#22D3EE",
		opacity: 0.1,
	},
	quickActionsRow: {
		flexDirection: "row",
		gap: 12,
		paddingHorizontal: 20,
		marginBottom: 12,
	},
	quickAction: {
		flex: 1,
		paddingVertical: 14,
		paddingHorizontal: 14,
		borderRadius: 14,
		borderWidth: 1,
		backgroundColor: "#0C142C",
	},
	quickActionTitle: {
		color: "#E2E8F0",
		fontSize: 16,
		fontWeight: "800",
		marginBottom: 4,
	},
	quickActionSubtitle: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 18,
	},
	languageRow: {
		flexDirection: "row",
		alignItems: "center",
		marginTop: 24,
	},
	languageLabel: {
		color: "#CBD5E1",
		marginRight: 8,
	},
	languageButton: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		marginHorizontal: 4,
		borderWidth: 1,
		borderRadius: 6,
		backgroundColor: "white",
		borderColor: "gray",
	},
	languageButtonActive: {
		backgroundColor: "#e0e0e0",
		borderColor: "black",
	},
	cardsContainer: {
		paddingHorizontal: 20,
		paddingTop: 12,
		paddingBottom: 32,
		gap: 24,
	},
	card: {
		borderColor: "rgba(255, 255, 255, 0.05)",
		backgroundColor: "#0F172A",
		borderRadius: 18,
		paddingHorizontal: 18,
		paddingVertical: 18,
		margin: 10,
		borderWidth: 1,
		shadowColor: "#000",
		shadowOpacity: 0.25,
		shadowRadius: 8,
		elevation: 3,
		width: "100%",
	},
	cardTitle: {
		fontSize: 18,
		fontWeight: "800",
		color: "white",
	},
	cardSubtitle: {
		fontSize: 13,
		color: "#CBD5E1",
		marginTop: 8,
		lineHeight: 18,
	},
	cardImage: {
		width: "100%",
		height: 230,
		borderRadius: 14,
		marginBottom: 14,
		backgroundColor: "#0B1226",
	},
});
