import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#010a30ff",
	},
	screenContent: {
		paddingBottom: 40,
	},
	heroCard: {
		marginHorizontal: 20,
		marginTop: 24,
		marginBottom: 16,
		padding: 20,
		borderRadius: 18,
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.18)",
		shadowColor: "#0EA5E9",
		shadowOpacity: 0.25,
		shadowRadius: 12,
		elevation: 5,
		gap: 10,
	},
	heroHeaderRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	heroAvatar: {
		width: 64,
		height: 64,
		borderRadius: 32,
		backgroundColor: "rgba(34, 211, 238, 0.16)",
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.2)",
	},
	heroGreeting: {
		color: "#94A3B8",
		fontSize: 14,
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	heroName: {
		color: "#E2E8F0",
		fontSize: 30,
		fontWeight: "900",
		marginTop: 2,
	},
	heroSubtitle: {
		color: "#CBD5E1",
		fontSize: 15,
		marginTop: 2,
		lineHeight: 20,
	},
	bubbleTop: {
		position: "absolute",
		top: -120,
		right: -100,
		width: 280,
		height: 280,
		borderRadius: 140,
		backgroundColor: "#0EA5E9",
		opacity: 0.15,
	},
	bubbleBottom: {
		position: "absolute",
		bottom: -140,
		left: -120,
		width: 320,
		height: 320,
		borderRadius: 160,
		backgroundColor: "#22D3EE",
		opacity: 0.1,
	},
	quickActionsRow: {
		gap: 12,
		paddingHorizontal: 20,
	},
	quickAction: {
		flex: 1,
		paddingVertical: 12,
		paddingStart: 12,
		paddingEnd: 12,
		borderRadius: 16,
		borderWidth: 1,
		//borderColor: "rgba(34, 211, 238, 0.18)",
		//backgroundColor: "#0F172A",
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
		backgroundColor: "#0F172A",
		//borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.06)",
		shadowColor: "#000",
		shadowOpacity: 0.25,
		shadowRadius: 12,
		elevation: 5,
		overflow: "hidden",
		position: "relative",
	},
	quickActionIconWrap: {
		width: 66,
		height: 66,
		borderRadius: 10,
		alignItems: "center",
		justifyContent: "center",
	},
	quickActionTextWrap: {
		flex: 1,
		marginLeft: 10,
		justifyContent: "space-between",
	},
	quickActionTitle: {
		color: "#E2E8F0",
		fontSize: 17,
		fontWeight: "800",
		marginBottom: 8,
	},
	quickActionSubtitle: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 18,
	},
});
