import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#0A0F2C",
	},
	scroll: {
		flex: 1,
	},
	content: {
		padding: 20,
		paddingBottom: 28,
	},
	heroCard: {
		padding: 20,
		borderRadius: 18,
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.18)",
		marginBottom: 16,
		shadowColor: "#0EA5E9",
		shadowOpacity: 0.3,
		shadowRadius: 14,
		elevation: 6,
	},
	heroBadge: {
		alignSelf: "flex-start",
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
		backgroundColor: "rgba(34, 211, 238, 0.12)",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.35)",
	},
	heroBadgeText: {
		color: "#E0F2FE",
		fontSize: 12,
		fontWeight: "700",
		letterSpacing: 0.3,
		textTransform: "uppercase",
	},
	heroName: {
		color: "#E2E8F0",
		fontSize: 26,
		fontWeight: "900",
		marginTop: 10,
	},
	heroSubtitle: {
		color: "#CBD5E1",
		fontSize: 15,
		marginTop: 6,
		lineHeight: 22,
	},
	heroMetaRow: {
		flexDirection: "row",
		gap: 10,
		marginTop: 12,
		flexWrap: "wrap",
	},
	heroMetaPill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 999,
		backgroundColor: "rgba(255, 255, 255, 0.06)",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.08)",
	},
	heroMetaText: {
		color: "#E2E8F0",
		fontWeight: "700",
	},
	label: {
		color: "#CBD5E1",
		marginBottom: 6,
	},
	input: {
		backgroundColor: "#0F172A",
		color: "#E2E8F0",
		borderRadius: 12,
		paddingHorizontal: 14,
		paddingVertical: 12,
		borderWidth: 1,
		borderColor: "#1E293B",
		marginBottom: 10,
	},
	saveButton: {
		paddingVertical: 12,
		borderRadius: 12,
		alignItems: "center",
		marginBottom: 24,
	},
	saveButtonEnabled: {
		backgroundColor: "#22D3EE",
	},
	saveButtonDisabled: {
		backgroundColor: "#1F2A44",
	},
	saveButtonText: {
		color: "white",
		fontWeight: "700",
	},
	languageRow: {
		flexDirection: "row",
		gap: 8,
	},
	languageButton: {
		flex: 1,
		paddingVertical: 12,
		borderRadius: 10,
		borderWidth: 1,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		gap: 8,
	},
	languageButtonActive: {
		borderColor: "#22D3EE",
		backgroundColor: "#0F172A",
	},
	languageButtonInactive: {
		borderColor: "#1E293B",
		backgroundColor: "#0C142C",
	},
	languageButtonText: {
		color: "#E2E8F0",
		fontWeight: "700",
	},
	sectionCard: {
		marginTop: 16,
		borderRadius: 14,
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.06)",
		shadowColor: "#000",
		shadowOpacity: 0.2,
		shadowRadius: 6,
		elevation: 3,
	},
	sectionHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingHorizontal: 14,
		paddingVertical: 12,
	},
	sectionTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 12,
	},
	sectionTitleWrapper: {
		flexDirection: "column",
		gap: 2,
	},
	sectionTitle: {
		color: "#E2E8F0",
		fontSize: 16,
		fontWeight: "800",
	},
	sectionSubtitle: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 18,
	},
	sectionBody: {
		paddingHorizontal: 16,
		paddingBottom: 16,
		gap: 10,
	},
	resetCard: {
		backgroundColor: "#0C142C",
		borderRadius: 12,
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.07)",
		padding: 14,
		gap: 12,
	},
	resetCardDanger: {
		backgroundColor: "rgba(244, 63, 94, 0.07)",
		borderColor: "rgba(244, 63, 94, 0.35)",
	},
	resetHeaderRow: {
		flexDirection: "row",
		gap: 12,
		alignItems: "center",
	},
	resetIcon: {
		width: 40,
		height: 40,
		borderRadius: 12,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "rgba(255, 255, 255, 0.06)",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.1)",
	},
	resetIconSafe: {
		borderColor: "rgba(34, 211, 238, 0.5)",
		backgroundColor: "rgba(34, 211, 238, 0.08)",
	},
	resetIconDanger: {
		borderColor: "rgba(244, 63, 94, 0.6)",
		backgroundColor: "rgba(244, 63, 94, 0.12)",
	},
	resetTextBlock: {
		flex: 1,
		gap: 4,
	},
	resetTitle: {
		color: "#E2E8F0",
		fontSize: 15,
		fontWeight: "800",
	},
	resetSubtitle: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 18,
	},
	resetActionButton: {
		borderRadius: 10,
		paddingVertical: 12,
		alignItems: "center",
		borderWidth: 1,
	},
	resetActionSecondary: {
		borderColor: "rgba(34, 211, 238, 0.6)",
		backgroundColor: "rgba(34, 211, 238, 0.12)",
	},
	resetActionDanger: {
		borderColor: "rgba(244, 63, 94, 0.7)",
		backgroundColor: "rgba(244, 63, 94, 0.12)",
	},
	resetActionText: {
		color: "#E0F2FE",
		fontWeight: "800",
	},
	resetActionTextDanger: {
		color: "#FEE2E2",
		fontWeight: "800",
	},
});
