import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#010a30ff",
	},
	bubbleTop: {
		position: "absolute",
		top: -120,
		right: -100,
		width: 280,
		height: 280,
		borderRadius: 140,
		backgroundColor: "#0EA5E9",
		opacity: 0.14,
	},
	bubbleBottom: {
		position: "absolute",
		bottom: -140,
		left: -120,
		width: 320,
		height: 320,
		borderRadius: 160,
		backgroundColor: "#22D3EE",
		opacity: 0.1,
	},
	screenContent: {
		paddingHorizontal: 20,
		paddingTop: 16,
		paddingBottom: 160,
		gap: 12,
	},
	subtitle: {
		color: "#CBD5E1",
		fontSize: 15,
		lineHeight: 20,
	},
	suggestionsWrap: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	suggestionChip: {
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.08)",
		backgroundColor: "#0F172A",
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderRadius: 14,
	},
	suggestionText: {
		color: "#E2E8F0",
		fontSize: 13,
		lineHeight: 18,
	},
	messagesCard: {
		backgroundColor: "#0B1436",
		borderRadius: 18,
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.16)",
		shadowColor: "#000",
		shadowOpacity: 0.25,
		shadowRadius: 12,
		elevation: 5,
		padding: 12,
		gap: 12,
	},
	messageRow: {
		flexDirection: "row",
		maxWidth: "100%",
	},
	bubbleAssistant: {
		alignSelf: "flex-start",
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.18)",
		borderRadius: 14,
		paddingVertical: 10,
		paddingHorizontal: 12,
		maxWidth: "88%",
	},
	bubbleUser: {
		alignSelf: "flex-end",
		backgroundColor: "#0EA5E9",
		borderRadius: 14,
		paddingVertical: 10,
		paddingHorizontal: 12,
		maxWidth: "88%",
	},
	assistantText: {
		color: "#E2E8F0",
		fontSize: 14,
		lineHeight: 20,
	},
	userText: {
		color: "#0B122F",
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "700",
	},
	inputBar: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		paddingHorizontal: 16,
		paddingTop: 10,
		backgroundColor: "rgba(1, 10, 48, 0.96)",
		borderTopWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.06)",
	},
	inputInner: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingHorizontal: 12,
		paddingVertical: 10,
		borderRadius: 16,
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.16)",
	},
	textInput: {
		flex: 1,
		color: "#E2E8F0",
		fontSize: 15,
		paddingVertical: 6,
	},
	sendButton: {
		width: 40,
		height: 40,
		borderRadius: 10,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#22D3EE",
	},
	sendIcon: {
		marginLeft: 1,
	},
	statusRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		marginTop: 8,
	},
	statusText: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 18,
	},
	loadingInline: {
		marginTop: 4,
	},
});
