import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#010a30ff",
	},
	bubbleTop: {
		position: "absolute",
		top: -120,
		right: -100,
		width: 280,
		height: 280,
		borderRadius: 140,
		backgroundColor: "#0EA5E9",
		opacity: 0.14,
	},
	bubbleBottom: {
		position: "absolute",
		bottom: -140,
		left: -120,
		width: 320,
		height: 320,
		borderRadius: 160,
		backgroundColor: "#22D3EE",
		opacity: 0.1,
	},
	screenContent: {
		paddingHorizontal: 20,
		paddingTop: 16,
		paddingBottom: 160,
		gap: 12,
	},
	subtitle: {
		color: "#CBD5E1",
		fontSize: 15,
		lineHeight: 20,
	},
	suggestionsWrap: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	suggestionChip: {
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.08)",
		backgroundColor: "#0F172A",
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderRadius: 14,
	},
	suggestionText: {
		color: "#E2E8F0",
		fontSize: 13,
		lineHeight: 18,
	},
	messagesCard: {
		backgroundColor: "#0B1436",
		borderRadius: 18,
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.16)",
		shadowColor: "#000",
		shadowOpacity: 0.25,
		shadowRadius: 12,
		elevation: 5,
		padding: 12,
		gap: 12,
	},
	messageRow: {
		flexDirection: "row",
		maxWidth: "100%",
	},
	bubbleAssistant: {
		alignSelf: "flex-start",
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.3)",
		shadowColor: "#22D3EE",
		shadowOpacity: 0.35,
		shadowRadius: 14,
		shadowOffset: { width: 0, height: 6 },
		elevation: 6,
		borderRadius: 14,
		paddingVertical: 10,
		paddingHorizontal: 12,
		maxWidth: "88%",
	},
	planPreview: {
		gap: 8,
	},
	metaRow: {
		flexDirection: "row",
		gap: 6,
		marginBottom: 6,
	},
	metaName: {
		color: "#94A3B8",
		fontSize: 11,
		fontWeight: "700",
	},
	metaTime: {
		color: "#64748B",
		fontSize: 11,
	},
	planHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	planTitle: {
		color: "#E2E8F0",
		fontSize: 13,
		fontWeight: "700",
	},
	planBadge: {
		backgroundColor: "rgba(34, 211, 238, 0.16)",
		paddingHorizontal: 10,
		paddingVertical: 4,
		borderRadius: 12,
		alignSelf: "flex-start",
	},
	planBadgeText: {
		color: "#22D3EE",
		fontSize: 12,
		fontWeight: "700",
	},
	planList: {
		marginTop: 4,
		gap: 6,
	},
	metaNameUser: {
		color: "#0B122F",
		fontSize: 11,
		fontWeight: "700",
	},
	metaTimeUser: {
		color: "#0B122F",
		fontSize: 11,
		opacity: 0.72,
	},
	planRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	planDot: {
		width: 6,
		height: 6,
		borderRadius: 3,
		backgroundColor: "#38BDF8",
	},
	planCta: {
		marginTop: 10,
		gap: 8,
		alignSelf: "flex-start",
	},
	planCtaRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	planActions: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		flexWrap: "wrap",
	},
	planStartButton: {
		backgroundColor: "#22D3EE",
		paddingVertical: 9,
		paddingHorizontal: 12,
		borderRadius: 12,
		minWidth: 120,
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#22D3EE",
		shadowOpacity: 0.35,
		shadowRadius: 10,
	},
	planStartText: {
		color: "#0B122F",
		fontSize: 13,
		fontWeight: "700",
	},
	planGhostButton: {
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.28)",
		paddingVertical: 9,
		paddingHorizontal: 12,
		borderRadius: 12,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "rgba(15, 23, 42, 0.8)",
	},
	planGhostText: {
		color: "#E2E8F0",
		fontSize: 13,
		fontWeight: "600",
	},
	planActionContent: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
	},
	bubbleUser: {
		alignSelf: "flex-end",
		backgroundColor: "#A5F3FC",
		borderWidth: 1,
		borderColor: "rgba(14, 165, 233, 0.45)",
		shadowColor: "#0EA5E9",
		shadowOpacity: 0.25,
		shadowRadius: 12,
		shadowOffset: { width: 0, height: 5 },
		elevation: 5,
		borderRadius: 14,
		paddingVertical: 10,
		paddingHorizontal: 12,
		maxWidth: "88%",
	},
	assistantText: {
		color: "#E2E8F0",
		fontSize: 14,
		lineHeight: 20,
	},
	userText: {
		color: "#0B122F",
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "700",
	},
	levelPrompt: {
		gap: 10,
	},
	levelPromptTitle: {
		color: "#E2E8F0",
		fontSize: 14,
		lineHeight: 20,
		fontWeight: "700",
	},
	levelOptions: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
	},
	levelOptionButton: {
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.35)",
		backgroundColor: "rgba(15, 23, 42, 0.9)",
		paddingVertical: 10,
		paddingHorizontal: 14,
		borderRadius: 14,
		shadowColor: "#22D3EE",
		shadowOpacity: 0.2,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 6 },
		elevation: 4,
		minWidth: 120,
	},
	levelOptionContent: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		justifyContent: "center",
	},
	levelOptionIcon: {
		width: 28,
		height: 28,
		borderRadius: 14,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#22D3EE",
		shadowColor: "#22D3EE",
		shadowOpacity: 0.3,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
	},
	levelOptionText: {
		color: "#E2E8F0",
		fontSize: 14,
		fontWeight: "700",
	},
	inputBar: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		paddingHorizontal: 16,
		paddingTop: 10,
		backgroundColor: "rgba(1, 10, 48, 0.96)",
		borderTopWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.06)",
	},
	inputInner: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		paddingHorizontal: 12,
		paddingVertical: 10,
		borderRadius: 16,
		backgroundColor: "#0F172A",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.16)",
	},
	textInput: {
		flex: 1,
		color: "#E2E8F0",
		fontSize: 15,
		paddingVertical: 6,
	},
	sendButton: {
		width: 40,
		height: 40,
		borderRadius: 10,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#22D3EE",
	},
	sendIcon: {
		marginLeft: 1,
	},
	statusRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		marginTop: 8,
	},
	statusText: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 18,
	},
	loadingInline: {
		marginTop: 4,
	},
});
