import { EXERCISE_KEYS } from "../state/useAppStore";

export const AI_COACH_API_URL =
	"https://unfull-hyperflexibly-marylynn.ngrok-free.dev/v1/chat/completions";
export const AI_COACH_MODEL = "local-llama";

export const REP_MIN = 1;
export const REP_MAX = 99;
export const ROUND_MIN = 1;
export const ROUND_MAX = 99;
export const HISTORY_WINDOW = 8;
export const MAX_TOKENS = 180;
export const TEMPERATURE = 0.1;

export const ALLOWED_EXERCISES = [
	EXERCISE_KEYS.SQUATS,
	EXERCISE_KEYS.PUSHUPS,
	EXERCISE_KEYS.HAMMER_CURLS,
	EXERCISE_KEYS.LATERAL_RAISES,
] as const;

export const TOPIC_KEYWORDS = [
	// Coach / intención
	"coach",
	"entrenador",
	"personal trainer",
	"plan",
	"plan de entrenamiento",
	"program",
	"programa",
	"rutina",
	"rutinas",
	"routine",
	"routines",
	"workout",
	"workouts",
	"entrenamiento",
	"entrenamientos",
	"training",
	"sesión",
	"session",

	// Objetivos
	"objetivo",
	"goals",
	"perder grasa",
	"fat loss",
	"bajar de peso",
	"weight loss",
	"ganar músculo",
	"build muscle",
	"hipertrofia",
	"hypertrophy",
	"fuerza",
	"strength",
	"resistencia",
	"endurance",
	"acondicionamiento",
	"conditioning",
	"movilidad",
	"mobility",
	"flexibilidad",
	"flexibility",
	"tonificación",
	"toning",
	"definición",
	"definition",

	// Parámetros (volumen / intensidad)
	"reps",
	"rep",
	"repeticiones",
	"repeticion",
	"sets",
	"set",
	"series",
	"peso",
	"weight",
	"carga",
	"load",
	"intensidad",
	"intensity",
	"esfuerzo",
	"effort",
	"rir",
	"rpe",
	"progresión",
	"progression",
	"sobrecarga progresiva",
	"progressive overload",
	"tempo",
	"cadencia",
	"técnica",
	"technique",
	"forma",
	"form",
	"rango de movimiento",
	"range of motion",
	"rom",

	// Descanso / frecuencia
	"descanso",
	"rest",
	"intervalo",
	"interval",
	"frecuencia",
	"frequency",
	"semana",
	"week",
	"veces",
	"days",
	"día",
	"duración",
	"duration",
	"rondas",
	"rounds",
	"series",
	"series",
	"circuito",
	"circuit",
	"intervalos",
	"intervals",
	"descansos",
	"rests",
	"pausas",
	"pauses",

	// Nivel
	"nivel",
	"level",
	"principiante",
	"beginner",
	"intermedio",
	"intermediate",
	"avanzado",
	"advanced",

	// Seguridad / salud
	"salud",
	"health",
	"bienestar",
	"wellness",
	"dolor",
	"pain",
	"lesión",
	"injury",
	"molestia",
	"discomfort",
	"contraindicación",
	"contraindication",
	"recuperación",
	"recovery",
	"fatiga",
	"fatigue",
	"sueño",
	"sleep",
	"estrés",
	"stress",
	"respiración",
	"breathing",
	"presión arterial",
	"blood pressure",
	"cardio",
	"calentamiento",
	"warm up",
	"warm-up",
	"enfriamiento",
	"cool down",
	"cool-down",
	"estiramiento",
	"stretching",

	// Población / datos del usuario
	"edad",
	"age",
	"años",
	"anos",
	"género",
	"genero",
	"gender",
	"hombre",
	"male",
	"mujer",
	"female",
	"altura",
	"height",
	"peso corporal",
	"body weight",
	"imc",
	"bmi",
	"historial",
	"history",
	"condición",
	"condition",

	// Equipo / material
	"mancuerna",
	"mancuernas",
	"dumbbell",
	"dumbbells",
	"pesas",
	"weights",
	"banda elástica",
	"resistance band",
	"equipo",
	"equipment",
	"sin equipo",
	"no equipment",

	// Músculos / zonas comunes
	"hombro",
	"shoulder",
	"deltoides",
	"deltoid",
	"bíceps",
	"biceps",
	"piernas",
	"legs",
	"glúteos",
	"glutes",
	"cuádriceps",
	"quadriceps",
	"core",
	"abdominales",
	"abs",
	"espalda",
	"back",

	// Tus ejercicios (nombres y variantes)
	"elevaciones laterales",
	"elevación lateral",
	"lateral raise",
	"lateral raises",
	"elevaciones laterales en paralelo",
	"parallel lateral raise",
	"curl martillo",
	"curl martillo alterno",
	"hammer curl",
	"alternating hammer curl",
	"sentadilla",
	"sentadillas",
	"squat",
	"squats",
	"flexiones",
	"flexión",
	"push up",
	"push ups",

	// Peticiones típicas al bot
	"instrucciones",
	"instructions",
	"cómo hacer",
	"how to",
	"paso a paso",
	"step by step",
	"consejos",
	"tips",
	"errores comunes",
	"common mistakes",
	"postura",
	"posture",
	"alineación",
	"alignment",
	"variación",
	"variation",
	"alternativa",
	"alternative",
	"progreso",
	"progress",
	"seguimiento",
	"tracking",
] as const;
