import { EXERCISE_KEYS } from "../state/useAppStore";

export const AI_COACH_API_URL =
	"https://unfull-hyperflexibly-marylynn.ngrok-free.dev/v1/chat/completions";
export const AI_COACH_MODEL = "local-llama";

export const REP_MIN = 1;
export const REP_MAX = 99;
export const ROUND_MIN = 1;
export const ROUND_MAX = 5;
export const HISTORY_WINDOW = 8;
export const MAX_TOKENS = 180;
export const TEMPERATURE = 0.1;

export const ALLOWED_EXERCISES = [
	EXERCISE_KEYS.SQUATS,
	EXERCISE_KEYS.PUSHUPS,
	EXERCISE_KEYS.HAMMER_CURLS,
	EXERCISE_KEYS.LATERAL_RAISES,
] as const;

export const TOPIC_KEYWORDS = [
	"rutina",
	"routine",
	"reps",
	"repes",
	"ejercicio",
	"exercise",
	"salud",
	"health",
	"fitness",
	"entrenamiento",
	"training",
	"flexiones",
	"levantamiento",
	"curls",
	"pesas",
	"weights",
	"weight",
	"abdominales",
	"abs",
	"instrucciones",
	"instructions",
	"forma",
	"form",
	"postura",
	"posture",
	"dolor",
	"pain",
	"calentamiento",
	"warm-up",
	"estiramiento",
	"stretching",
	"squat",
	"sentadilla",
	"push",
	"flexion",
	"hammer",
	"curl",
	"lateral",
	"raise",
	"mancuerna",
	"dumbbell",
	"edad",
	"age",
	"años",
	"anos",
	"gender",
	"male",
	"female",
	"hombre",
	"mujer",
	"frecuencia",
	"frequency",
	"veces",
	"week",
	"semana",
	"nivel",
	"level",
	"principiante",
	"beginner",
	"intermedio",
	"intermediate",
	"avanzado",
	"advanced",
	"repeticiones",
	"repetitions",
	"series",
	"sets",
	"descanso",
	"rest",
	"intervalo",
	"interval",
	"dificultad",
	"difficulty",
	"peso",
	"weight",
	"cuerpo",
	"body",
	"saludable",
	"healthy",
	"habito",
	"habit",
	"actividad",
	"activity",
	"movimiento",
	"movement",
	"cardio",
	"flexibilidad",
	"flexibility",
	"resistencia",
	"endurance",
	"fuerza",
	"strength",
	"tonificación",
	"toning",
	"definición",
	"definition",
	"masa muscular",
	"muscle mass",
	"bienestar",
	"wellness",
	"vida",
	"life",
	"salud",
	"health",
	"ejercicios",
	"exercises",
	"entrenamientos",
	"workouts",
	"rutinas",
	"routines",
] as const;
