import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#010a30ff",
	},
	screenContent: {
		paddingHorizontal: 20,
		paddingBottom: 32,
	},
	header: {
		marginTop: 20,
		marginBottom: 16,
		gap: 6,
	},
	title: {
		color: "#E2E8F0",
		fontSize: 28,
		fontWeight: "900",
	},
	subtitle: {
		color: "#94A3B8",
		fontSize: 14,
		lineHeight: 20,
	},
	list: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "space-between",
		rowGap: 12,
		columnGap: 12,
		marginTop: 6,
	},
	card: {
		borderRadius: 20,
		overflow: "hidden",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.25)",
		shadowColor: "#0EA5E9",
		shadowOpacity: 0.2,
		shadowRadius: 10,
		elevation: 5,
		width: "48%",
		position: "relative",
	},
	cardBackground: {
		height: 200,
		width: "100%",
		justifyContent: "flex-end",
	},
	cardImage: {
		resizeMode: "cover",
	},
	cardOverlay: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(5, 10, 30, 0.55)",
	},
	cardOverlayDisabled: {
		backgroundColor: "rgba(5, 10, 30, 0.78)",
	},
	cardContent: {
		padding: 16,
		paddingTop: 22,
		gap: 16,
	},
	selectButtonContainer: {
		position: "absolute",
		top: 10,
		right: 10,
		zIndex: 2,
	},
	cardBody: {
		gap: 6,
		alignItems: "center",
	},
	selectButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 999,
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.22)",
		backgroundColor: "rgba(255,255,255,0.08)",
	},
	selectButtonOff: {
		borderColor: "rgba(255,255,255,0.14)",
		backgroundColor: "rgba(0,0,0,0.15)",
	},
	selectButtonText: {
		color: "#E2E8F0",
		fontWeight: "800",
		fontSize: 13,
	},
	cardTitle: {
		color: "#F8FAFC",
		fontSize: 20,
		fontWeight: "900",
		letterSpacing: 0.2,
		textAlign: "center",
	},
	cardFooter: {
		marginTop: 6,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	circleButton: {
		width: 42,
		height: 42,
		borderRadius: 21,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: "rgba(34, 211, 238, 0.45)",
		backgroundColor: "rgba(34, 211, 238, 0.18)",
	},
	circleButtonText: {
		color: "#22D3EE",
		fontSize: 18,
		fontWeight: "900",
	},
	count: {
		color: "#F8FAFC",
		fontSize: 18,
		fontWeight: "900",
		minWidth: 40,
		textAlign: "center",
	},
	footer: {
		marginTop: 18,
		gap: 10,
	},
	selectionText: {
		color: "#CBD5E1",
		fontSize: 13,
	},
	bottomBar: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: "rgba(1,10,48,0.94)",
		paddingHorizontal: 20,
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: "rgba(34, 211, 238, 0.2)",
		shadowColor: "#0EA5E9",
		shadowOpacity: 0.2,
		shadowRadius: 10,
		elevation: 8,
		gap: 8,
	},
	bottomMeta: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	startButton: {
		marginTop: 6,
		backgroundColor: "#22D3EE",
		borderRadius: 16,
		paddingVertical: 14,
		alignItems: "center",
		shadowColor: "#22D3EE",
		shadowOpacity: 0.25,
		shadowRadius: 10,
		elevation: 4,
	},
	startText: {
		color: "#0B122F",
		fontSize: 16,
		fontWeight: "900",
	},
	disabled: {
		opacity: 0.35,
	},
});
